# -*- coding: utf-8 -*-
"""PYTHON TASK.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-IScirSch9uCXT3QI5mLmWxQ99ESv7XB

# step 1: importing data
"""

import pandas as pd
file = pd.read_excel('Ecommerce Data.xlsx')

"""# step 2: E.D.A."""

file.head(2)

file.tail()

file.shape

file.dtypes

file.info()

file.describe()

"""# step 3: data cleaning

#### step 3.1: deticting nulls
"""

file.isnull().sum()

"""#### step 3.2: deticting duplecits"""

file.duplicated().sum()

duplicated=file[file.duplicated()]
duplicated

"""#### step 3.3: nulls"""

file = file[file['Customer Gender'].notna()]
file = file[file['Location'].notna()]
file = file[file['Zone'].notna()]
file = file[file['Delivery Type'].notna()]
file = file[file['Product Category'].notna()]
file = file[file['SubCategory'].notna()]
file.isnull().sum()

file.info()

"""#### step 3.4: Removing Duplicates

##### No Duplicates

#### Step 4: Analysis
"""

file['Product Category'].value_counts()

file['Product'].value_counts().head(5)

len(file['Product'].unique())

pivot_table = file.pivot_table(index='Product Category', values='Rating', aggfunc='mean').sort_values(by='Rating', ascending=False)
pivot_table

file['Rating_Cat']=pd.cut(file.Rating,bins=[0,1,2,3,4,5],labels=['VD','DS','N','S','VS'])

file['Rating_Cat']

file[['Rating','Rating_Cat']]

pivot_table = file.pivot_table(index='Product Category', values='Rating', aggfunc='mean', margins=True).sort_values(by='Rating', ascending=False)
index_order = list(pivot_table.index)
index_order.remove('All')
index_order.append('All')
pivot_table = pivot_table.reindex(index_order)
pivot_table

"""### group by

"""

total_sales_by_location = file.groupby('Location')['Sale Price'].sum().sort_values(ascending=False).head(10)
total_sales_by_location

import plotly.express as px

pivot_table = file.pivot_table(index='Product Category', values='Order Quantity', aggfunc='count').sort_values(by='Order Quantity', ascending=False)

fig = px.pie(
    values=pivot_table['Order Quantity'],
    names=pivot_table.index,
    title='Order Quantity by Product Category'
)
fig.update_layout(title_x=0.5)
fig.show()

pivot_table = file.pivot_table(index='Product Category', values='Order Quantity', aggfunc='count').sort_values(by='Order Quantity', ascending=False)
pivot_table